apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app    # Add labels in metadata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/YOUR_PROJECT_ID/my-app:v1 
        ports:
        - containerPort: 8080
          name: http         # Add port name
        resources:          # Add resource limits
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:     # Add health checks
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http